// import _ from 'lodash'; // Importing lodash
import _ from 'lodash'; // Importing lodash
export const imageUrl = 'https://assets-futuremortgage-com.s3.amazonaws.com/';

export const settingConfig = {
  fieldsToCheck: ['homeValue', 'loanAmount', 'creditScore', 'loanPercentage'],

  fields: [
    'address',
    'loanType',
    'loanPercentage',
    'amortizationType',
    'aprRequested',
    'propertyType',
    'propertyUse',
    'homeValue',
    'loanAmount',
    'creditScore',
    'annualIncome',
    'isVaEligible',
    'amortizationType',
    'propertyType',
    'propertyUse',
  ],
  compensation: [
    {
      key: 1,
      actValue: '1',
      value: 'Universal Plan',
    },
    {
      key: 2,
      actValue: '2',

      value: 'Branch Manager',
    },
    {
      key: 3,
      actValue: '3',

      value: 'Division Manager',
    },
  ],
  clientStatus: [
    {
      key: 1,
      value: 'New',
    },
    {
      key: 2,
      value: 'Responded',
    },
    {
      key: 3,
      value: 'Nurturing',
    },
    {
      key: 4,
      value: 'Working',
    },
    {
      key: 5,
      value: 'Past Client',
    },
  ],
  rowsPerPage: [
    {
      key: '10',
      value: 10,
    },
    {
      key: '20',
      value: 20,
    },
    {
      key: '30',
      value: 30,
    },
    {
      key: '40',
      value: 40,
    },
    {
      key: '50',
      value: 50,
    },
  ],
  status: [
    {
      key: 1,
      value: 'New',
    },
    {
      key: 2,
      value: 'Responded',
    },
    {
      key: 3,
      value: 'Nurturing',
    },
    {
      key: 4,
      value: 'Working',
    },
    {
      key: 5,
      value: 'Past Client',
    },
  ],
  currentCompany: [
    {
      key: 1,
      value: 'New',
    },
    {
      key: 2,
      value: 'Responded',
    },
    {
      key: 3,
      value: 'Nurturing',
    },
    {
      key: 4,
      value: 'Working',
    },
    {
      key: 5,
      value: 'Past Client',
    },
  ],
  leadSource: [
    {
      key: 1,
      value: 'Self Sourced',
    },
    {
      key: 2,
      value: 'Bankrate',
    },
    {
      key: 3,
      value: 'LendingTree',
    },
    {
      key: 4,
      value: 'Past Client Referral',
    },
    {
      key: 5,
      value: 'Company Website',
    },
    {
      key: 6,
      value: 'CBH Homes',
    },
    {
      key: 7,
      value: 'Agent Referral',
    },
    {
      key: 8,
      value: 'Boise Hunter Homes',
    },
    {
      key: 9,
      value: 'Bauscher Real Estate',
    },
    {
      key: 10,
      value: 'McFerrin Real Estate',
    },
    {
      key: 11,
      value: 'Templeton Real Estate',
    },
  ],
  isVaEligible: [
    {
      key: 1,
      value: 'Yes',
    },
    {
      key: 2,
      value: 'No',
    },
  ],
  amortizationType: [
    {
      key: 1,
      value: 'Fixed',
    },
    {
      key: 2,
      value: 'Adjustable',
    },
  ],
  propertyType: [
    {
      key: 1,
      value: 'Single Family',
    },
    {
      key: 2,
      value: 'Townhome',
    },
    {
      key: 3,
      value: 'Condo',
    },
  ],
  propertyUse: [
    {
      key: 1,
      value: 'Primary Residence',
    },
    {
      key: 2,
      value: 'Second Home',
    },
    {
      key: 3,
      value: 'Investment',
    },
  ],
  loanTag: [
    {
      key: 1,
      value: 'Application Intaket',
    },
    {
      key: 2,
      value: 'Pre-Qualification',
    },
    {
      key: 3,
      value: 'Pre-Approved',
    },
    {
      key: 4,
      value: 'Loan Setup',
    },
    {
      key: 5,
      value: 'Disclosures Sent',
    },
    {
      key: 6,
      value: 'In Underwriting',
    },
    {
      key: 7,
      value: 'Conditionally Approved',
    },
    {
      key: 8,
      value: 'Re-submitted',
    },
    {
      key: 9,
      value: 'Clear to Close',
    },
    {
      key: 10,
      value: 'Docs out',
    },
    {
      key: 11,
      value: 'Docs Signed',
    },
    {
      key: 12,
      value: 'Loan Funded',
    },
    {
      key: 13,
      value: 'Broker Check Recieved',
    },
    {
      key: 14,
      value: 'Commission Paid',
    },
    {
      key: 15,
      value: 'Adverse',
    },
  ],
  campaign: [
    {
      key: 1,
      value: 'Application Intaket',
    },
    {
      key: 2,
      value: 'Pre-Qualification',
    },
    {
      key: 3,
      value: 'Pre-Approved',
    },
    {
      key: 4,
      value: 'Loan Setup',
    },
    {
      key: 5,
      value: 'Disclosures Sent',
    },
    {
      key: 6,
      value: 'In Underwriting',
    },
    {
      key: 7,
      value: 'Conditionally Approved',
    },
    {
      key: 8,
      value: 'Re-submitted',
    },
    {
      key: 9,
      value: 'Clear to Close',
    },
    {
      key: 10,
      value: 'Docs out',
    },
    {
      key: 11,
      value: 'Docs Signed',
    },
    {
      key: 12,
      value: 'Loan Funded',
    },
    {
      key: 13,
      value: 'Broker Check Recieved',
    },
    {
      key: 14,
      value: 'Commission Paid',
    },
    {
      key: 15,
      value: 'Adverse',
    },
    {
      key: 16,
      value: 'Adaptive dynamic complexity',
    },
  ],
  builderCompany: [
    {
      key: 1,
      value: 'Application Intaket',
    },
    {
      key: 2,
      value: 'Pre-Qualification',
    },
    {
      key: 3,
      value: 'Pre-Approved',
    },
    {
      key: 4,
      value: 'Loan Setup',
    },
    {
      key: 5,
      value: 'Disclosures Sent',
    },
    {
      key: 6,
      value: 'In Underwriting',
    },
    {
      key: 7,
      value: 'Conditionally Approved',
    },
    {
      key: 8,
      value: 'Re-submitted',
    },
    {
      key: 9,
      value: 'Clear to Close',
    },
    {
      key: 10,
      value: 'Docs out',
    },
    {
      key: 11,
      value: 'Docs Signed',
    },
    {
      key: 12,
      value: 'Loan Funded',
    },
    {
      key: 13,
      value: 'Broker Check Recieved',
    },
    {
      key: 14,
      value: 'Commission Paid',
    },
    {
      key: 15,
      value: 'Adverse',
    },
  ],

  stateList: [
    {
      label: 'Andaman and Nicobar Islands',
      id: 1,
      code: 'AN',
      districts: [
        { label: 'Nicobar', id: 1 },
        { label: 'North and Middle Andaman', id: 2 },
        { label: 'South Andaman', id: 3 },
      ],
    },
    {
      label: 'Andhra Pradesh',
      id: 2,
      code: 'AP',
      districts: [
        { label: 'Anantapur', id: 4 },
        { label: 'Chittoor', id: 5 },
        { label: 'East Godavari', id: 6 },
        { label: 'Guntur', id: 7 },
        { label: 'Krishna', id: 8 },
        { label: 'Kurnool', id: 9 },
        { label: 'Prakasam', id: 10 },
        { label: 'Srikakulam', id: 11 },
        { label: 'Visakhapatnam', id: 12 },
        { label: 'Vizianagaram', id: 13 },
        { label: 'West Godavari', id: 14 },
        { label: 'YSR Kadapa', id: 15 },
      ],
    },
    {
      label: 'Arunachal Pradesh',
      id: 3,
      code: 'AR',
      districts: [
        { label: 'Anjaw', id: 16 },
        { label: 'Changlang', id: 17 },
        { label: 'East Kameng', id: 18 },
        { label: 'East Siang', id: 19 },
        { label: 'Kamle', id: 20 },
        { label: 'Kra Daadi', id: 21 },
        { label: 'Kurung Kumey', id: 22 },
        { label: 'Lohit', id: 23 },
        { label: 'Longding', id: 24 },
        { label: 'Lower Dibang Valley', id: 25 },
        { label: 'Lower Siang', id: 26 },
        { label: 'Namsai', id: 27 },
        { label: 'Papum Pare', id: 28 },
        { label: 'Siang', id: 29 },
        { label: 'Tawang', id: 30 },
        { label: 'Tirap', id: 31 },
        { label: 'Upper Dibang Valley', id: 32 },
        { label: 'Upper Siang', id: 33 },
        { label: 'Upper Subansiri', id: 34 },
        { label: 'West Kameng', id: 35 },
        { label: 'West Siang', id: 36 },
      ],
    },
    {
      label: 'Assam',
      id: 4,
      code: 'AS',
      districts: [
        { label: 'Baksa', id: 37 },
        { label: 'Barpeta', id: 38 },
        { label: 'Bongaigaon', id: 39 },
        { label: 'Cachar', id: 40 },
        { label: 'Charaideo', id: 41 },
        { label: 'Chirang', id: 42 },
        { label: 'Darrang', id: 43 },
        { label: 'Dhemaji', id: 44 },
        { label: 'Dibrugarh', id: 45 },
        { label: 'Dima Hasao', id: 46 },
        { label: 'Goalpara', id: 47 },
        { label: 'Golaghat', id: 48 },
        { label: 'Hailakandi', id: 49 },
        { label: 'Hojai', id: 50 },
        { label: 'Jorhat', id: 51 },
        { label: 'Kamrup', id: 52 },
        { label: 'Kamrup Metropolitan', id: 53 },
        { label: 'Karbi Anglong', id: 54 },
        { label: 'Karimganj', id: 55 },
        { label: 'Kokrajhar', id: 56 },
        { label: 'Lakhimpur', id: 57 },
        { label: 'Majuli', id: 58 },
        { label: 'Morigaon', id: 59 },
        { label: 'Nagaon', id: 60 },
        { label: 'Nalbari', id: 61 },
        { label: 'Sivasagar', id: 62 },
        { label: 'Sonitpur', id: 63 },
        { label: 'South Salmara-Mankachar', id: 64 },
        { label: 'Tinsukia', id: 65 },
        { label: 'Udalguri', id: 66 },
        { label: 'West Karbi Anglong', id: 67 },
      ],
    },

    {
      label: 'Bihar',
      id: 5,
      code: 'BR',
      districts: [
        { label: 'Araria', id: 68 },
        { label: 'Arwal', id: 69 },
        { label: 'Aurangabad', id: 70 },
        { label: 'Banka', id: 71 },
        { label: 'Begusarai', id: 72 },
        { label: 'Bhagalpur', id: 73 },
        { label: 'Bhojpur', id: 74 },
        { label: 'Buxar', id: 75 },
        { label: 'Darbhanga', id: 76 },
        { label: 'East Champaran', id: 77 },
        { label: 'Gaya', id: 78 },
        { label: 'Gopalganj', id: 79 },
        { label: 'Jamui', id: 80 },
        { label: 'Jehanabad', id: 81 },
        { label: 'Kaimur', id: 82 },
        { label: 'Katihar', id: 83 },
        { label: 'Khagaria', id: 84 },
        { label: 'Kishanganj', id: 85 },
        { label: 'Lakhisarai', id: 86 },
        { label: 'Madhepura', id: 87 },
        { label: 'Madhubani', id: 88 },
        { label: 'Munger', id: 89 },
        { label: 'Muzaffarpur', id: 90 },
        { label: 'Nalanda', id: 91 },
        { label: 'Nawada', id: 92 },
        { label: 'Patna', id: 93 },
        { label: 'Purnia', id: 94 },
        { label: 'Rohtas', id: 95 },
        { label: 'Saharsa', id: 96 },
        { label: 'Samastipur', id: 97 },
        { label: 'Saran', id: 98 },
        { label: 'Sheikhpura', id: 99 },
        { label: 'Sheohar', id: 100 },
        { label: 'Sitamarhi', id: 101 },
        { label: 'Siwan', id: 102 },
        { label: 'Supaul', id: 103 },
        { label: 'Vaishali', id: 104 },
        { label: 'West Champaran', id: 105 },
      ],
    },
    {
      label: 'Chhattisgarh',
      id: 6,
      code: 'CG',
      districts: [
        { label: 'Balod', id: 106 },
        { label: 'Baloda Bazar', id: 107 },
        { label: 'Balrampur', id: 108 },
        { label: 'Bastar', id: 109 },
        { label: 'Bemetara', id: 110 },
        { label: 'Bijapur', id: 111 },
        { label: 'Bilaspur', id: 112 },
        { label: 'Dantewada', id: 113 },
        { label: 'Dhamtari', id: 114 },
        { label: 'Durg', id: 115 },
        { label: 'Gariaband', id: 116 },
        { label: 'Janjgir-Champa', id: 117 },
        { label: 'Jashpur', id: 118 },
        { label: 'Kabirdham', id: 119 },
        { label: 'Kanker', id: 120 },
        { label: 'Kondagaon', id: 121 },
        { label: 'Korba', id: 122 },
        { label: 'Koriya', id: 123 },
        { label: 'Mahasamund', id: 124 },
        { label: 'Mungeli', id: 125 },
        { label: 'Narayanpur', id: 126 },
        { label: 'Raigarh', id: 127 },
        { label: 'Raipur', id: 128 },
        { label: 'Rajnandgaon', id: 129 },
        { label: 'Sukma', id: 130 },
        { label: 'Surajpur', id: 131 },
        { label: 'Surguja', id: 132 },
      ],
    },
    {
      label: 'Chandigarh',
      id: 7,
      code: 'CH',
      districts: [{ label: 'Chandigarh', id: 133 }],
    },
    {
      label: 'Dadra and Nagar Haveli',
      id: 8,
      code: 'DH',
      districts: [{ label: 'Dadra and Nagar Haveli', id: 134 }],
    },
    {
      label: 'Daman and Diu',
      id: 9,
      code: 'DD',
      districts: [
        { label: 'Daman', id: 135 },
        { label: 'Diu', id: 136 },
      ],
    },
    {
      label: 'Delhi',
      id: 10,
      code: 'DL',
      districts: [
        { label: 'Central Delhi', id: 137 },
        { label: 'East Delhi', id: 138 },
        { label: 'New Delhi', id: 139 },
        { label: 'North Delhi', id: 140 },
        { label: 'North East Delhi', id: 141 },
        { label: 'North West Delhi', id: 142 },
        { label: 'Shahdara', id: 143 },
        { label: 'South Delhi', id: 144 },
        { label: 'South West Delhi', id: 145 },
        { label: 'West Delhi', id: 146 },
      ],
    },
    {
      label: 'Goa',
      id: 11,
      code: 'GA',
      districts: [
        { label: 'North Goa', id: 147 },
        { label: 'South Goa', id: 148 },
      ],
    },
    {
      label: 'Gujarat',
      id: 12,
      code: 'GJ',
      districts: [
        { label: 'Ahmedabad', id: 149 },
        { label: 'Amreli', id: 150 },
        { label: 'Anand', id: 151 },
        { label: 'Aravalli', id: 152 },
        { label: 'Banaskantha', id: 153 },
        { label: 'Bharuch', id: 154 },
        { label: 'Bhavnagar', id: 155 },
        { label: 'Botad', id: 156 },
        { label: 'Chhota Udepur', id: 157 },
        { label: 'Dahod', id: 158 },
        { label: 'Dang', id: 159 },
        { label: 'Devbhoomi Dwarka', id: 160 },
        { label: 'Gandhinagar', id: 161 },
        { label: 'Gir Somnath', id: 162 },
        { label: 'Jamnagar', id: 163 },
        { label: 'Junagadh', id: 164 },
        { label: 'Kutch', id: 165 },
        { label: 'Kheda', id: 166 },
        { label: 'Mahisagar', id: 167 },
        { label: 'Mehsana', id: 168 },
        { label: 'Morbi', id: 169 },
        { label: 'Narmada', id: 170 },
        { label: 'Navsari', id: 171 },
        { label: 'Panchmahal', id: 172 },
        { label: 'Patan', id: 173 },
        { label: 'Porbandar', id: 174 },
        { label: 'Rajkot', id: 175 },
        { label: 'Sabarkantha', id: 176 },
        { label: 'Surat', id: 177 },
        { label: 'Surendranagar', id: 178 },
        { label: 'Tapi', id: 179 },
        { label: 'Vadodara', id: 180 },
        { label: 'Valsad', id: 181 },
      ],
    },
    {
      label: 'Haryana',
      id: 13,
      code: 'HR',
      districts: [
        { label: 'Ambala', id: 182 },
        { label: 'Bhiwani', id: 183 },
        { label: 'Charkhi Dadri', id: 184 },
        { label: 'Faridabad', id: 185 },
        { label: 'Fatehabad', id: 186 },
        { label: 'Gurugram', id: 187 },
        { label: 'Hisar', id: 188 },
        { label: 'Jhajjar', id: 189 },
        { label: 'Jind', id: 190 },
        { label: 'Kaithal', id: 191 },
        { label: 'Karnal', id: 192 },
        { label: 'Kurukshetra', id: 193 },
        { label: 'Mahendragarh', id: 194 },
        { label: 'Nuh', id: 195 },
        { label: 'Palwal', id: 196 },
        { label: 'Panchkula', id: 197 },
        { label: 'Panipat', id: 198 },
        { label: 'Rewari', id: 199 },
        { label: 'Rohtak', id: 200 },
        { label: 'Sirsa', id: 201 },
        { label: 'Sonipat', id: 202 },
        { label: 'Yamunanagar', id: 203 },
      ],
    },
    {
      label: 'Himachal Pradesh',
      id: 14,
      code: 'HP',
      districts: [
        { label: 'Bilaspur', id: 204 },
        { label: 'Chamba', id: 205 },
        { label: 'Hamirpur', id: 206 },
        { label: 'Kangra', id: 207 },
        { label: 'Kullu', id: 208 },
        { label: 'Mandi', id: 209 },
        { label: 'Shimla', id: 210 },
        { label: 'Sirmaur', id: 211 },
        { label: 'Solan', id: 212 },
        { label: 'Una', id: 213 },
      ],
    },
    {
      label: 'Jammu and Kashmir',
      id: 15,
      code: 'JK',
      districts: [
        { label: 'Anantnag', id: 214 },
        { label: 'Bandipora', id: 215 },
        { label: 'Baramulla', id: 216 },
        { label: 'Budgam', id: 217 },
        { label: 'Doda', id: 218 },
        { label: 'Ganderbal', id: 219 },
        { label: 'Jammu', id: 220 },
        { label: 'Kathua', id: 221 },
        { label: 'Kishtwar', id: 222 },
        { label: 'Kulgam', id: 223 },
        { label: 'Kupwara', id: 224 },
        { label: 'Poonch', id: 225 },
        { label: 'Pulwama', id: 226 },
        { label: 'Rajouri', id: 227 },
        { label: 'Samba', id: 228 },
        { label: 'Shopian', id: 229 },
        { label: 'Srinagar', id: 230 },
        { label: 'Udhampur', id: 231 },
      ],
    },
    {
      label: 'Jharkhand',
      id: 16,
      code: 'JH',
      districts: [
        { label: 'Bokaro', id: 232 },
        { label: 'Chatra', id: 233 },
        { label: 'Deoghar', id: 234 },
        { label: 'Dhanbad', id: 235 },
        { label: 'Dumka', id: 236 },
        { label: 'Garhwa', id: 237 },
        { label: 'Giridih', id: 238 },
        { label: 'Godda', id: 239 },
        { label: 'Gumla', id: 240 },
        { label: 'Hazaribagh', id: 241 },
        { label: 'Jamtara', id: 242 },
        { label: 'Khunti', id: 243 },
        { label: 'Koderma', id: 244 },
        { label: 'Latehar', id: 245 },
        { label: 'Lohardaga', id: 246 },
        { label: 'Pakur', id: 247 },
        { label: 'Palamu', id: 248 },
        { label: 'Ramgarh', id: 249 },
        { label: 'Ranchi', id: 250 },
        { label: 'Sahibganj', id: 251 },
        { label: 'Seraikela Kharsawan', id: 252 },
        { label: 'Simdega', id: 253 },
        { label: 'West Singhbhum', id: 254 },
      ],
    },
    {
      label: 'Karnataka',
      id: 17,
      code: 'KA',
      districts: [
        { label: 'Bagalkot', id: 255 },
        { label: 'Bangalore Rural', id: 256 },
        { label: 'Bangalore Urban', id: 257 },
        { label: 'Belagavi', id: 258 },
        { label: 'Ballari', id: 259 },
        { label: 'Bidar', id: 260 },
        { label: 'Chamarajanagar', id: 261 },
        { label: 'Chikkaballapur', id: 262 },
        { label: 'Chikkamagaluru', id: 263 },
        { label: 'Chitradurga', id: 264 },
        { label: 'Dakshina Kannada', id: 265 },
        { label: 'Davanagere', id: 266 },
        { label: 'Hassan', id: 267 },
        { label: 'Haveri', id: 268 },
        { label: 'Kodagu', id: 269 },
        { label: 'Kolar', id: 270 },
        { label: 'Koppal', id: 271 },
        { label: 'Mandya', id: 272 },
        { label: 'Mysuru', id: 273 },
        { label: 'Raichur', id: 274 },
        { label: 'Ramanagara', id: 275 },
        { label: 'Shivamogga', id: 276 },
        { label: 'Tumakuru', id: 277 },
        { label: 'Udupi', id: 278 },
        { label: 'Uttara Kannada', id: 279 },
        { label: 'Vijayapura', id: 280 },
        { label: 'Yadgir', id: 281 },
      ],
    },
    {
      label: 'Kerala',
      id: 18,
      code: 'KL',
      districts: [
        { label: 'Alappuzha', id: 282 },
        { label: 'Ernakulam', id: 283 },
        { label: 'Idukki', id: 284 },
        { label: 'Kottayam', id: 285 },
        { label: 'Kozhikode', id: 286 },
        { label: 'Malappuram', id: 287 },
        { label: 'Palakkad', id: 288 },
        { label: 'Pathanamthitta', id: 289 },
        { label: 'Thiruvananthapuram', id: 290 },
        { label: 'Thrissur', id: 291 },
        { label: 'Wayanad', id: 292 },
      ],
    },
    {
      label: 'Ladakh',
      id: 19,
      code: 'LA',
      districts: [
        { label: 'Leh', id: 293 },
        { label: 'Kargil', id: 294 },
      ],
    },
    {
      label: 'Lakshadweep',
      id: 20,
      code: 'LD',
      districts: [
        { label: 'Agatti', id: 295 },
        { label: 'Amini', id: 296 },
        { label: 'Andrott', id: 297 },
        { label: 'Bangaram', id: 298 },
        { label: 'Bithra', id: 299 },
        { label: 'Chetlat', id: 300 },
        { label: 'Kavaratti', id: 301 },
        { label: 'Kalapeni', id: 302 },
        { label: 'Kiltan', id: 303 },
        { label: 'Minicoy', id: 304 },
        { label: 'Suheli', id: 305 },
      ],
    },
    {
      label: 'Madhya Pradesh',
      id: 21,
      code: 'MP',
      districts: [
        { label: 'Alirajpur', id: 306 },
        { label: 'Anuppur', id: 307 },
        { label: 'Ashoknagar', id: 308 },
        { label: 'Balaghat', id: 309 },
        { label: 'Barwani', id: 310 },
        { label: 'Betul', id: 311 },
        { label: 'Bhind', id: 312 },
        { label: 'Bhopal', id: 313 },
        { label: 'Burhanpur', id: 314 },
        { label: 'Chhatarpur', id: 315 },
        { label: 'Chhindwara', id: 316 },
        { label: 'Damoh', id: 317 },
        { label: 'Datia', id: 318 },
        { label: 'Dewas', id: 319 },
        { label: 'Dhar', id: 320 },
        { label: 'Dindori', id: 321 },
        { label: 'Guna', id: 322 },
        { label: 'Gwalior', id: 323 },
        { label: 'Harda', id: 324 },
        { label: 'Hoshangabad', id: 325 },
        { label: 'Indore', id: 326 },
        { label: 'Jabalpur', id: 327 },
        { label: 'Jhabua', id: 328 },
        { label: 'Katni', id: 329 },
        { label: 'Khandwa', id: 330 },
        { label: 'Khargone', id: 331 },
        { label: 'Mandla', id: 332 },
        { label: 'Mandsaur', id: 333 },
        { label: 'Morena', id: 334 },
        { label: 'Narsinghpur', id: 335 },
        { label: 'Neemuch', id: 336 },
        { label: 'Panchmahal', id: 337 },
        { label: 'Panna', id: 338 },
        { label: 'Raisen', id: 339 },
        { label: 'Rajgarh', id: 340 },
        { label: 'Ratlam', id: 341 },
        { label: 'Rewa', id: 342 },
        { label: 'Sagar', id: 343 },
        { label: 'Satna', id: 344 },
        { label: 'Sehore', id: 345 },
        { label: 'Seoni', id: 346 },
        { label: 'Shahdol', id: 347 },
        { label: 'Shajapur', id: 348 },
        { label: 'Sheopur', id: 349 },
        { label: 'Shivpuri', id: 350 },
        { label: 'Singrauli', id: 351 },
        { label: 'Tikamgarh', id: 352 },
        { label: 'Ujjain', id: 353 },
        { label: 'Umaria', id: 354 },
        { label: 'Vidisha', id: 355 },
      ],
    },
    {
      label: 'Maharashtra',
      id: 22,
      code: 'MH',
      districts: [
        { label: 'Ahmednagar', id: 356 },
        { label: 'Akola', id: 357 },
        { label: 'Amravati', id: 358 },
        { label: 'Aurangabad', id: 359 },
        { label: 'Beed', id: 360 },
        { label: 'Bhandara', id: 361 },
        { label: 'Buldhana', id: 362 },
        { label: 'Chandrapur', id: 363 },
        { label: 'Dhule', id: 364 },
        { label: 'Gadchiroli', id: 365 },
        { label: 'Gondia', id: 366 },
        { label: 'Hingoli', id: 367 },
        { label: 'Jalgaon', id: 368 },
        { label: 'Jalna', id: 369 },
        { label: 'Kolhapur', id: 370 },
        { label: 'Latur', id: 371 },
        { label: 'Mumbai City', id: 372 },
        { label: 'Mumbai Suburban', id: 373 },
        { label: 'Nagpur', id: 374 },
        { label: 'Nanded', id: 375 },
        { label: 'Nandurbar', id: 376 },
        { label: 'Nasik', id: 377 },
        { label: 'Osmanabad', id: 378 },
        { label: 'Palghar', id: 379 },
        { label: 'Parbhani', id: 380 },
        { label: 'Pune', id: 381 },
        { label: 'Raigad', id: 382 },
        { label: 'Ratnagiri', id: 383 },
        { label: 'Satara', id: 384 },
        { label: 'Sindhudurg', id: 385 },
        { label: 'Solapur', id: 386 },
        { label: 'Thane', id: 387 },
        { label: 'Wardha', id: 388 },
        { label: 'Washim', id: 389 },
        { label: 'Yavatmal', id: 390 },
      ],
    },
    {
      label: 'Manipur',
      id: 23,
      code: 'MN',
      districts: [
        { label: 'Bishnupur', id: 391 },
        { label: 'Chandel', id: 392 },
        { label: 'Churachandpur', id: 393 },
        { label: 'Imphal East', id: 394 },
        { label: 'Imphal West', id: 395 },
        { label: 'Jiribam', id: 396 },
        { label: 'Kangpokpi', id: 397 },
        { label: 'Noney', id: 398 },
        { label: 'Senapati', id: 399 },
        { label: 'Tamenglong', id: 400 },
        { label: 'Tengnoupal', id: 401 },
        { label: 'Thoubal', id: 402 },
        { label: 'Ukhrul', id: 403 },
      ],
    },
    {
      label: 'Meghalaya',
      id: 24,
      code: 'ML',
      districts: [
        { label: 'East Garo Hills', id: 404 },
        { label: 'East Khasi Hills', id: 405 },
        { label: 'Jaintia Hills', id: 406 },
        { label: 'Ri-Bhoi', id: 407 },
        { label: 'West Garo Hills', id: 408 },
        { label: 'West Khasi Hills', id: 409 },
      ],
    },
    {
      label: 'Mizoram',
      id: 25,
      code: 'MZ',
      districts: [
        { label: 'Aizawl', id: 410 },
        { label: 'Champhai', id: 411 },
        { label: 'Kolasib', id: 412 },
        { label: 'Lawngtlai', id: 413 },
        { label: 'Lunglei', id: 414 },
        { label: 'Mamit', id: 415 },
        { label: 'Saiha', id: 416 },
        { label: 'Serchhip', id: 417 },
      ],
    },
    {
      label: 'Nagaland',
      id: 26,
      code: 'NL',
      districts: [
        { label: 'Dimapur', id: 418 },
        { label: 'Kiphire', id: 419 },
        { label: 'Kohima', id: 420 },
        { label: 'Longleng', id: 421 },
        { label: 'Mokokchung', id: 422 },
        { label: 'Mon', id: 423 },
        { label: 'Peren', id: 424 },
        { label: 'Phek', id: 425 },
        { label: 'Tuensang', id: 426 },
        { label: 'Wokha', id: 427 },
        { label: 'Zunheboto', id: 428 },
      ],
    },
    {
      label: 'Odisha',
      id: 27,
      code: 'OR',
      districts: [
        { label: 'Angul', id: 429 },
        { label: 'Balangir', id: 430 },
        { label: 'Balasore', id: 431 },
        { label: 'Bargarh', id: 432 },
        { label: 'Bhadrak', id: 433 },
        { label: 'Boudh', id: 434 },
        { label: 'Cuttack', id: 435 },
        { label: 'Debagarh', id: 436 },
        { label: 'Dhenkanal', id: 437 },
        { label: 'Gajapati', id: 438 },
        { label: 'Ganjam', id: 439 },
        { label: 'Jagatsinghpur', id: 440 },
        { label: 'Jajpur', id: 441 },
        { label: 'Kalahandi', id: 442 },
        { label: 'Kandhamal', id: 443 },
        { label: 'Kendrapara', id: 444 },
        { label: 'Kendujhar', id: 445 },
        { label: 'Khurda', id: 446 },
        { label: 'Koraput', id: 447 },
        { label: 'Malkangiri', id: 448 },
        { label: 'Mayurbhanj', id: 449 },
        { label: 'Nabarangpur', id: 450 },
        { label: 'Nayagarh', id: 451 },
        { label: 'Nuapada', id: 452 },
        { label: 'Puri', id: 453 },
        { label: 'Rayagada', id: 454 },
        { label: 'Sambalpur', id: 455 },
        { label: 'Subarnapur', id: 456 },
        { label: 'Sundargarh', id: 457 },
      ],
    },
    {
      label: 'Puducherry',
      id: 28,
      code: 'PY',
      districts: [
        { label: 'Karaikal', id: 458 },
        { label: 'Mahe', id: 459 },
        { label: 'Puducherry', id: 460 },
        { label: 'Yanam', id: 461 },
      ],
    },
    {
      code: 'RJ',
      label: 'Rajasthan',
      districts: [
        { label: 'Ajmer', id: 1 },
        { label: 'Alwar', id: 2 },
        { label: 'Banswara', id: 3 },
        { label: 'Baran', id: 4 },
        { label: 'Barmer', id: 5 },
        { label: 'Bharatpur', id: 6 },
        { label: 'Bhilwara', id: 7 },
        { label: 'Bikaner', id: 8 },
        { label: 'Bundi', id: 9 },
        { label: 'Chittorgarh', id: 10 },
        { label: 'Churu', id: 11 },
        { label: 'Dausa', id: 12 },
        { label: 'Dholpur', id: 13 },
        { label: 'Dungarpur', id: 14 },
        { label: 'Hanumangarh', id: 15 },
        { label: 'Jaipur', id: 16 },
        { label: 'Jaisalmer', id: 17 },
        { label: 'Jalor', id: 18 },
        { label: 'Jhalawar', id: 19 },
        { label: 'Jhunjhunu', id: 20 },
        { label: 'Jodhpur', id: 21 },
        { label: 'Karauli', id: 22 },
        { label: 'Kota', id: 23 },
        { label: 'Nagaur', id: 24 },
        { label: 'Pali', id: 25 },
        { label: 'Rajsamand', id: 26 },
        { label: 'Sawai Madhopur', id: 27 },
        { label: 'Sri Ganganagar', id: 28 },
        { label: 'Tonk', id: 29 },
        { label: 'Udaipur', id: 30 },
      ],
    },
    {
      code: 'TN',
      label: 'Tamil Nadu',
      districts: [
        { label: 'Chengalpattu', id: 31 },
        { label: 'Kancheepuram', id: 32 },
        { label: 'Kanyakumari', id: 33 },
        { label: 'Karur', id: 34 },
        { label: 'Krishnagiri', id: 35 },
        { label: 'Madurai', id: 36 },
        { label: 'Nagapattinam', id: 37 },
        { label: 'Namakkal', id: 38 },
        { label: 'Nilgiris', id: 39 },
        { label: 'Perambalur', id: 40 },
        { label: 'Pudukkottai', id: 41 },
        { label: 'Ramanathapuram', id: 42 },
        { label: 'Salem', id: 43 },
        { label: 'Sivaganga', id: 44 },
        { label: 'Tiruvallur', id: 45 },
        { label: 'Tiruchirappalli', id: 46 },
        { label: 'Tirunelveli', id: 47 },
        { label: 'Tiruppur', id: 48 },
        { label: 'Vellore', id: 49 },
        { label: 'Villupuram', id: 50 },
        { label: 'Virudhunagar', id: 51 },
      ],
    },
    {
      code: 'TS',
      label: 'Telangana',
      districts: [
        { label: 'Adilabad', id: 52 },
        { label: 'Hyderabad', id: 53 },
        { label: 'Jagityal', id: 54 },
        { label: 'Jangaon', id: 55 },
        { label: 'Jayashankar', id: 56 },
        { label: 'Jogulamba', id: 57 },
        { label: 'Khammam', id: 58 },
        { label: 'Karimnagar', id: 59 },
        { label: 'Mahabubnagar', id: 60 },
        { label: 'Mancherial', id: 61 },
        { label: 'Medak', id: 62 },
        { label: 'Medchal', id: 63 },
        { label: 'Mulugu', id: 64 },
        { label: 'Nagarkurnool', id: 65 },
        { label: 'Nalgonda', id: 66 },
        { label: 'Nirmal', id: 67 },
        { label: 'Nizamabad', id: 68 },
        { label: 'Peddapalli', id: 69 },
        { label: 'Rajanna', id: 70 },
        { label: 'Rangareddy', id: 71 },
        { label: 'Sangareddy', id: 72 },
        { label: 'Siddipet', id: 73 },
        { label: 'Suryapet', id: 74 },
        { label: 'Vikarabad', id: 75 },
        { label: 'Warangal', id: 76 },
        { label: 'Yadadri Bhuvanagiri', id: 77 },
      ],
    },
    {
      code: 'TR',
      label: 'Tripura',
      districts: [
        { label: 'Dhalai', id: 78 },
        { label: 'Gomati', id: 79 },
        { label: 'Kailashahar', id: 80 },
        { label: 'North Tripura', id: 81 },
        { label: 'Sepahijala', id: 82 },
        { label: 'South Tripura', id: 83 },
        { label: 'Unakoti', id: 84 },
        { label: 'West Tripura', id: 85 },
      ],
    },
    {
      code: 'UP',
      label: 'Uttar Pradesh',
      districts: [
        { label: 'Agra', id: 86 },
        { label: 'Aligarh', id: 87 },
        { label: 'Allahabad', id: 88 },
        { label: 'Ambedkar Nagar', id: 89 },
        { label: 'Amethi', id: 90 },
        { label: 'Amroha', id: 91 },
        { label: 'Auraiya', id: 92 },
        { label: 'Azamgarh', id: 93 },
        { label: 'Badaun', id: 94 },
        { label: 'Baghpat', id: 95 },
        { label: 'Bahraich', id: 96 },
        { label: 'Ballia', id: 97 },
        { label: 'Balrampur', id: 98 },
        { label: 'Banda', id: 99 },
        { label: 'Barabanki', id: 100 },
      ],
    },
    {
      code: 'UK',
      label: 'Uttarakhand',
      districts: [
        { label: 'Almora', id: 141 },
        { label: 'Bageshwar', id: 142 },
        { label: 'Chamoli', id: 143 },
        { label: 'Champawat', id: 144 },
        { label: 'Dehradun', id: 145 },
        { label: 'Haridwar', id: 146 },
        { label: 'Nainital', id: 147 },
        { label: 'Pauri Garhwal', id: 148 },
        { label: 'Pithoragarh', id: 149 },
        { label: 'Rudraprayag', id: 150 },
        { label: 'Tehri Garhwal', id: 151 },
        { label: 'Udham Singh Nagar', id: 152 },
        { label: 'Uttarkashi', id: 153 },
      ],
    },
    {
      code: 'WB',
      label: 'West Bengal',
      districts: [
        { label: 'Alipurduar', id: 154 },
        { label: 'Bankura', id: 155 },
        { label: 'Birbhum', id: 156 },
        { label: 'Cooch Behar', id: 157 },
        { label: 'Dakshin Dinajpur', id: 158 },
        { label: 'Darjeeling', id: 159 },
        { label: 'Hooghly', id: 160 },
        { label: 'Howrah', id: 161 },
        { label: 'Jalpaiguri', id: 162 },
        { label: 'Jhargram', id: 163 },
        { label: 'Kolkata', id: 164 },
        { label: 'Malda', id: 165 },
        { label: 'Murshidabad', id: 166 },
        { label: 'Nadia', id: 167 },
        { label: 'North 24 Parganas', id: 168 },
        { label: 'Purba Bardhaman', id: 169 },
        { label: 'Purulia', id: 170 },
        { label: 'South 24 Parganas', id: 171 },
        { label: 'Uttar Dinajpur', id: 172 },
      ],
    },
  ],

  units: [
    {
      key: 1,
      value: 'Application Intaket',
    },
    {
      key: 2,
      value: 'Pre-Qualification',
    },
    {
      key: 3,
      value: 'Pre-Approved',
    },
    {
      key: 4,
      value: 'Loan Setup',
    },
    {
      key: 5,
      value: 'Disclosures Sent',
    },
    {
      key: 6,
      value: 'In Underwriting',
    },
    {
      key: 7,
      value: 'Conditionally Approved',
    },
    {
      key: 8,
      value: 'Re-submitted',
    },
    {
      key: 9,
      value: 'Clear to Close',
    },
    {
      key: 10,
      value: 'Docs out',
    },
    {
      key: 11,
      value: 'Docs Signed',
    },
    {
      key: 12,
      value: 'Loan Funded',
    },
    {
      key: 13,
      value: 'Broker Check Recieved',
    },
    {
      key: 14,
      value: 'Commission Paid',
    },
    {
      key: 15,
      value: 'Adverse',
    },
  ],

  getSetting(prop, condition) {
    const object = _.find(this[prop], {
      key: condition,
    });

    return object ? object.value : '';
  },
};
